### ISSUE TITLE
오타발견!

### ISSUE THREAD

**Issue by yoruck2** [ODDNERO/MeaningOut#1]
https://github.com/ODDNERO/MeaningOut/blob/7c043b6910af64883a08a85cab093209f7664557/MeaningOut/Extension/ldentifierProtocol.swift#L10

ldentifier 가 아니라 Identifier를 쓰려고 하셨나요?
ldentifier -> Identifier

i 대문자와 L 소문자가 너무 닮아 생긴 이슈..
앞으로 구분할 수 있도록 트레이닝 문제를 내어드리겠습니다.

lIlIlIl|Il|IIlIlI|lllIl
이중에 i 대문자는 몇개일까~요?

**Comment by ODDNERO** [comment]
덕분에 오타 수정했습니다 🙃...

<img width="300" alt="image" src="https://github.com/ODDNERO/MeaningOut/assets/144796294/f20445d1-2fe3-4160-b26e-3eace2ba6aa9">
<br/> 이제 구분 능력이 생겼네요 9개 ^-^
